version: '2'
networks:
  myshop:
    driver: bridge
services:
  proxy:
    image: shop-proxy:latest
    ports: ["81:80"]
    networks:
      - myshop
  products:
    image: products-api:latest
    networks:
      - myshop
  ratings:
    image: ratings-api:latest
    networks:
      - myshop
  recommandations:
    image: recommandations-api:latest
    networks:
      - myshop
  shop:
    image: shop-front:latest
    networks:
      - myshop
    environment:
      - SHOP_PRODUCTS_API_URL=http://10.0.75.2:81/products
      - SHOP_RATINGS_API_URL=http://10.0.75.2:81/ratings
      - SHOP_RECOMMANDATIONS_API_URL=http://10.0.75.2:81/recommandations